version: '3'

services:
    product-service:
        build: ./product
        volumes:
            - ./product:/usr/src/app
        ports:
            - 5566:1234

    website:
        image: php:apache
        volumes:
            - ./website:/var/www/html
        ports:
            - 2266:80
        depends_on:
            - product-service